import type { NoteTerms } from '../api/types'

/** A sensible empty note the app opens on, so it never starts pinned to a bundled
    term sheet. The user builds from here, loads a bundled config, or uploads one. */
export function blankNote(): NoteTerms {
  return {
    name: 'New note',
    issuer: '',
    issuer_id: '',
    maturity: 1.0,
    payment_freq: 'quarterly',
    coupon_pa: 0.10,
    coupon_barrier: 0.70,
    autocall_barrier: 1.0,
    autocall_start_period: 1,
    knock_in_barrier: 0.60,
    memory: true,
    coupon_basket: 'worst_of',
    autocall_basket: 'worst_of',
    one_star_level: null,
    autocall_step_down: null,
    autocall_floor: null,
    coupon_at_autocall_only: false,
    zenith: false,
    capital_guarantee: 0,
    upside_cap: null,
    principal_protection: 1.0,
    note_type: 'phoenix',
    participation_downside: 'full',
    participation_upside: 'linear',
    participation_basket: 'worst_of',
    protection_level: 1.0,
    participation_rate: 1.0,
    participation_strike: 1.0,
    knockout_level: null,
    knockout_payout: 1.0,
    digital_payout: 0,
    participation_periodic: false,
    period_cap: null,
    issuer_description: '',
    issuer_rating_sp: '',
    issuer_rating_moody: '',
    issuer_rating_fitch: '',
    note_description: '',
    tickers: { '^GSPC': 'S&P 500' },
    issue_date: null,
    underlyings: {},
  }
}
