"""
tests/test_calibrator.py
------------------------
`core/calibrator.py` had no tests. The bug that prompted these: `mu` was computed
as `mean(log-return)/dt + 0.5*theta` using the RAW theta, but theta is then clamped
to PARAM_BOUNDS max 0.50 (~71% vol) and the simulator mean-reverts to the CLAMPED
value. The half-theta added back is supposed to cancel the log-Euler step's -V/2;
when the two thetas differ, it doesn't, and the difference is pure invented drift.

Measured on a 92%-vol series before the fix: +15.4% per year of upward drift that
is not in the data — which on a knock-in product understates barrier risk, the one
direction you never want to be wrong in.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from core.calibrator import PARAM_BOUNDS, HestonCalibrator
from core.simulator import HestonMultiSimulator


def _series(vol: float, *, n: int = 1300, seed: int = 5) -> pd.DataFrame:
    """A GBM series with a known annualised mean log-return of -0.5*vol**2."""
    rng = np.random.default_rng(seed)
    dt = 1 / 252
    lr = rng.normal(-0.5 * vol ** 2 * dt, vol * np.sqrt(dt), n)
    return (pd.DataFrame({"HI": 100 * np.exp(np.cumsum(lr))},
                         index=pd.bdate_range("2019-01-01", periods=n)),
            float(lr.mean() / dt))


def _simulated_log_growth(cal, *, n_paths: int = 20_000, seed: int = 3) -> float:
    p = cal.params[0]
    sim = HestonMultiSimulator(
        params=cal.params, corr_SS=np.eye(1), corr_VV=np.eye(1),
        corr_SV=np.eye(1) * p.rho, n_paths=n_paths, seed=seed,
        dt_grid=np.full(252, 1 / 252), t_dof=cal.t_dof)
    S = sim.run(engine="numpy")["S_paths"][0]
    return float(np.log(S[:, -1] / S[:, 0]).mean())


@pytest.mark.parametrize("vol,clamps", [(0.35, False), (0.92, True)])
def test_simulated_growth_matches_the_calibration_window(vol, clamps):
    """The invariant `mu`'s derivation claims: simulated log-growth reproduces the
    realised log-growth of the calibration window.

    The high-vol case is the one that matters — it is the only one where theta hits
    its bound, and the only one the bug affected. Reverting `mu` to use the raw
    theta puts the error at ~+0.154/yr, so the 0.05 bound turns red — mutation-
    verified, not assumed.
    """
    df, realised = _series(vol)
    cal = HestonCalibrator(prices_df=df, calib_years=5).calibrate()
    assert (cal.params[0].theta >= PARAM_BOUNDS["theta"][1] - 1e-9) is clamps, (
        f"fixture must {'' if clamps else 'not '}hit the theta bound")
    err = _simulated_log_growth(cal) - realised
    assert abs(err) < 0.05, (
        f"simulated log-growth is {err:+.4f}/yr away from realised — mu and the "
        "theta the simulator uses have drifted apart")


def test_calibrated_parameters_are_inside_their_bounds():
    """Every parameter the simulator receives must be inside PARAM_BOUNDS: it
    validates them and raises, so an out-of-bounds estimate is a hard failure at
    run time rather than a bad number."""
    df, _ = _series(0.92)
    cal = HestonCalibrator(prices_df=df, calib_years=5).calibrate()
    for p in cal.params:
        for field in ("kappa", "theta", "xi", "rho"):
            lo, hi = PARAM_BOUNDS[field]
            assert lo <= getattr(p, field) <= hi, f"{p.name}.{field} out of bounds"
        assert p.V0 > 0 and np.isfinite(p.mu)
        p.validate()


def test_feller_is_enforced_after_clamping():
    """The nudge must leave 2*kappa*theta > xi**2. The simulator only warns, so a
    violated Feller condition silently degrades the variance path near zero."""
    df, _ = _series(0.92)
    cal = HestonCalibrator(prices_df=df, calib_years=5).calibrate()
    for p in cal.params:
        ok, margin = p.feller_condition()
        assert ok, f"{p.name}: Feller violated after calibration (margin {margin:.4f})"


def _heston_series(true_rho: float, *, n_days: int = 1300, seed: int = 0,
                   xi: float = 0.5) -> pd.DataFrame:
    """A price series generated BY the project's own simulator at a known rho —
    so 'did the calibrator recover it' has an exact answer."""
    from core.simulator import HestonMultiSimulator, HestonParams
    p = [HestonParams(name="X", S0=100.0, kappa=2.0, theta=0.04, xi=xi,
                      rho=true_rho, V0=0.04, mu=0.05)]
    sim = HestonMultiSimulator(params=p, corr_SS=np.eye(1), corr_VV=np.eye(1),
                               corr_SV=np.eye(1) * true_rho, n_paths=1, seed=seed,
                               dt_grid=np.full(n_days, 1 / 252))
    S = sim.run(engine="numpy")["S_paths"][0][0]
    return pd.DataFrame({"X": S}, index=pd.bdate_range("2019-01-01", periods=len(S)))


def test_the_leverage_estimator_is_flat_and_this_is_a_known_limitation():
    """PINS A KNOWN DEFECT — read this before trusting a calibrated rho.

    `_estimate_leverage` correlates daily returns against changes in a rolling
    realised variance. Run against series this repo GENERATED at a known rho, it
    recovers essentially the same small number whatever the truth:

        true -0.90 -> -0.04      true  0.00 -> +0.00
        true -0.70 -> -0.04      true +0.40 -> +0.04
        true -0.40 -> -0.03

    The sign survives; the magnitude does not. Every calibration therefore
    simulates with almost no leverage, so paths carry far less downside skew than
    the underlying really has — which understates knock-in probability on exactly
    the worst-of notes this app prices.

    The signal is not absent from the data, it is absent at the DAILY horizon:
    the same series' 21-day aggregated skew separates cleanly (-0.68 at rho=-0.9
    through +0.39 at rho=+0.4), which is where a replacement estimator should
    look. That is a real piece of quant work with its own validation needs, not a
    patch — so this test pins the current behaviour rather than papering over it.
    If you replace the estimator, this test SHOULD fail; make it assert recovery
    and delete this docstring.
    """
    got = {r: HestonCalibrator(prices_df=_heston_series(r), calib_years=99)
                .calibrate().params[0].rho
           for r in (-0.9, 0.0)}
    # The whole point: a 0.9 spread in the truth collapses to under 0.2 recovered.
    assert abs(got[-0.9] - got[0.0]) < 0.2, (
        f"the estimator now discriminates ({got}) — if that is deliberate, this "
        "test is obsolete: assert recovery instead")
    assert got[-0.9] > -0.3, f"recovered {got[-0.9]:+.3f}: far weaker than the true -0.90"
